apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-weights-pvc
  labels:
    app: backend-weights
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
